"""Add go_outside column

Revision ID: d3140e629e11
Revises: 4ba6d297e76b
Create Date: 2025-05-16 22:20:15.568661

"""
from typing import Sequence, Union

from app.utils import should_go_outside
from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3140e629e11'
down_revision: Union[str, None] = '4ba6d297e76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind_measurements', sa.Column('go_outside', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    connection = op.get_bind()

    rows = connection.execute(text("SELECT id, wind_kph FROM wind_measurements")).fetchall()

    for row in rows:
        go_outside = should_go_outside(row.wind_kph)
        connection.execute(
            text("UPDATE wind_measurements SET go_outside = :go_outside WHERE id = :id"),
            {"go_outside": go_outside, "id": row.id}
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind_measurements', 'go_outside')
    # ### end Alembic commands ###
